train_dir: /content/sa-1b/train
val_dir: /content/sa-1b/validate
train_annotation_file: /content/sa-1b/annotations/instances_train2017.json
val_annotation_file: /content/sa-1b/annotations/instances_val2017.json